name: build github pages
on:
  workflow_dispatch:

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Check out source
        uses: actions/checkout@v2
        with:
          path: source

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./source
        run: npm install

      - name: Install vue-eslint
        working-directory: ./source
        run: npm i --save-dev eslint-plugin-vue@next

      - name: build sourcecode
        working-directory: ./source
        run: ./node_modules/.bin/vue-cli-service build

      - name: copy build code from source to pages
        run: /bin/cp -r ./source/dist/* ./gh-pages/

      - name: Commit update
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: '.'
          author_name: Slluxx
          author_email: Slluxx@users.noreply.github.com
          branch: gh-pages
          branch_mode: throw
          cwd: 'gh-pages'
          default_author: github_actor
          message: 'GitHub Actions - update API'
          pathspec_error_handling: ignore
          pull: '--no-rebase'
          push: true
          remove: ''
          tag: ''
